### ISSUE TITLE
Да се вземе конфигурация за ъплинка от NetX

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#1]

**Comment by krokodilerian** [comment]
IPv4 -
Network:  185.108.141.88/30
NetX: 185.108.141.89
FOP: 185.108.141.90

IPv6 -
Network: 2a01:b760:1::/127
NetX: 2a01:b760:1::0
FOP: 2a01:b760:1::1

Static IPv6 networks:
2a01:b760:abc:2::/64
2a01:b760:abc:3::/64
2a01:b760:abc:4::/64
2a01:b760:abc:5::/64
