### ISSUE TITLE
Nagios + SNMP traps

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#11]
- [x] Инсталация на nagios
 - [ ] Thresholds / alerting
 - [ ] Jabber integration
 - [ ] Host templated (AP/Server/Streamer/Restreamer/Overflow
 - [ ] Автоматична генерация?
 - [ ] Local SNMP

**Comment by zeridon** [comment]
cc @Arcopix като са готови нещата за стрийм мониторинга ще ги интегрираме

**Comment by zeridon** [comment]
* Нагиос-а е инсталиран (nagios3)
* базов сетъп с core суичовете
* един снмп чек за цисковските дивайси
* snmptt е инсталиран но все още не е пълно функционален

**Comment by zeridon** [comment]
Инсталация:
 * apt-get install nagios3
 * move apache to 8081
 * proxy_pass from nginx to apache
 * PW in /etc/nagios3/htpasswd.users

Switch monitoring:
 * UPTIME
 * TRAPS (incomplete)
 * Port status as needed (mostly done on cisco)

**Comment by zeridon** [comment]
traps work (shitty stuff)
