### ISSUE TITLE
Graphite

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#12]
Да се инсталира и конфигурира graphite за събиране на пърформанс данни

 - [x] инсталиране на graphite
 - [x] конфигурация на aggregated/relayed pipeline (за блеклист/агрегации извън web интерфейса)
 - [x] rewriting на метрики с грозни имена
 - [x] сервиране НЕ от dev server-а на джанго
 - [x] преместване на отделен порт за да не се цапа дефолтния vhost

**Comment by zeridon** [comment]
@ignisf да си изберем порт (ще трябва на tessera-та (#14)

**Comment by zeridon** [comment]
graphite vhost is on port 8080 in fe98c77c19c2687b5e30ee9a19dd11239d326cc1
