### ISSUE TITLE
collectd

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#13]
- [x] Base collectd install
 - [x] Local machine monitoring
 - [x] Server listen testing
 - [x] Слухтене във всички VLAN-и
 - [x] SNMP конфиг за мониторване на трафик от switch-овете
 - [x] Примерен конфиг за AP-та и eagle

**Comment by zeridon** [comment]
@krokodilerian @ignisf ще имаме ли да наглеждаме нещо извън мениджмънт VLAN-а (и еевентуално видео-то)

**Comment by ignisf** [comment]
Не. Никой не се е обадил да правим подобно нещо, слушаме само в management.

**Comment by zeridon** [comment]
Encryption на collectd трафика (макар че в изолиран VLAN няма голям смисъл)?

**Comment by ignisf** [comment]
не, няма

**Comment by zeridon** [comment]
Central collectd.conf added in [monitoring/collectd/server/collectd.conf] (monitoring/collectd/server/collectd.conf)
Commit: 33f7f5f5ef65b1fe716f281554023795e1388fe6

**Comment by ignisf** [comment]
Just FYI, засега съм включил тези модули на AP-тата:
```
CONFIG_PACKAGE_collectd=y
CONFIG_PACKAGE_collectd-mod-contextswitch=y
CONFIG_PACKAGE_collectd-mod-cpu=y
CONFIG_PACKAGE_collectd-mod-interface=y
CONFIG_PACKAGE_collectd-mod-irq=y
CONFIG_PACKAGE_collectd-mod-iwinfo=y
CONFIG_PACKAGE_collectd-mod-load=y
CONFIG_PACKAGE_collectd-mod-network=y
CONFIG_PACKAGE_collectd-mod-wireless=y
```

**Comment by zeridon** [comment]
mod-iwinfo, mod-wireless и [wlstats-gather.sh](https://github.com/OpenFest/openfest-network/blob/master/monitoring/collectd/scripts/wlstats-gather/wlstats-gather.sh) се припокриват на не малко места. Дали няма да е по смислено да си забъркаме наша си комбинация.

see: 576736ebf931cbcfcd8500def0022d41f58d23e0

**Comment by zeridon** [comment]
collectd вече наглежда (406b88e28496d3d1de5d9be18dea04a9b7b016e8) и чертае (68a6c3f09a0cd371175add3594c0aaac2ee07e34) трафика от суичовете
