### ISSUE TITLE
syslog, който да слуша в мрежата

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#16]
- [x] инсталация на syslog сървър идва с OS ще се сменя ли?
 - [x] конфигурация да слуша на мрежа (tcp and udp)
 - [x] Конфигурация на филтри/мутатори
 - [x] конфигурация за съхранение на логовете
 - [x] testing

**Comment by zeridon** [comment]
Prerequisite for #28

**Comment by zeridon** [comment]
Initial testing complete
Closed in: b8d4660ab31fe9a206f415c807c32573fb2eebe7

**Comment by zeridon** [comment]
Слухти във текущите тестови vlan-и и в бъдещите прод
