### ISSUE TITLE
Да се нарисува схема на мрежата с портовете

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#20]

**Comment by krokodilerian** [comment]
https://github.com/OpenFest/openfest/blob/master/2015/schemes/network.pdf - това трябва да съдържа всичко в себе си, вкл. кое е trunk и кое не. Забележки?

**Comment by zeridon** [comment]
Ако мрежовата адресация/VLAN-ите ще е в друг документ аз съм ок.

**Comment by krokodilerian** [comment]
Адресацията и vlan-ите са в https://github.com/OpenFest/openfest/blob/master/2015/network/main , като май ще ги пипна, че не ми харесват така адресите.

**Comment by krokodilerian** [comment]
И адресацията е ок.
