### ISSUE TITLE
Нетагнати портове от management vlan на NOC Switch

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#22]

**Comment by krokodilerian** [comment]
Текущ статус на портовете:


Port      Name               Status       Vlan       Duplex  Speed Type
Gi1/1     coresw             connected    trunk      a-full a-1000 10/100/1000-TX
Gi1/2     f2sw               connected    trunk      a-full a-1000 10/100/1000-TX
Gi1/3                        notconnect   1            auto   auto 10/100/1000-TX
Gi1/4                        notconnect   1            auto   auto 10/100/1000-TX
Gi1/5     AP1                notconnect   1            auto   auto 10/100/1000-TX
Gi1/6                        notconnect   1            auto   auto 10/100/1000-TX
Gi1/7     videoteam/bulgaria notconnect   103          auto   auto 10/100/1000-TX
Gi1/8                        notconnect   1            auto   auto 10/100/1000-TX
Gi1/9                        notconnect   1            auto   auto 10/100/1000-TX
Gi1/10                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/11                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/12                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/13                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/14                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/15                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/16                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/17                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/18                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/19                       notconnect   1            auto   auto 10/100/1000-TX
Gi1/20    wireless           notconnect   102          auto   auto 10/100/1000-TX
Gi1/21    wireless           notconnect   102          auto   auto 10/100/1000-TX
Gi1/22    wireless           notconnect   102          auto   auto 10/100/1000-TX
Gi1/23    wireless           notconnect   102          auto   auto 10/100/1000-TX
Gi1/24    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/25    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/26    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/27    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/28    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/29    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/30    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/31    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/32    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/33    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/34    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/35    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/36    mgmt               notconnect   100          auto   auto 10/100/1000-TX
Gi1/37    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/38    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/39    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/40    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/41    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/42    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/43    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/44    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/45    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/46    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/47    wired              notconnect   101          auto   auto 10/100/1000-TX
Gi1/48    wired              notconnect   101          auto   auto 10/100/1000-TX

**Comment by zeridon** [comment]
Сложете някакви надписи кои портове за какво са (онези нетагнатите в 
края) върху самото желязо, че да не се чудят нокаджиите.
