### ISSUE TITLE
Централен syslog на AP-тата

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#28]

**Comment by zeridon** [comment]
@zeridon: create central collector setup for syslog

Отделно стандартен сислог стрийм ли ще е? Със всичките facility/priority комбота или просто на някое от локалните ще блъскаме?

Предпочитам хостовете на ап-тата да са нещо от типа на APXX-<Floor>-<loc/chan/etc> ще улесни парсенето на сислога

**Comment by krokodilerian** [comment]
те ще са по host, и аз май си мислех да е един rsyslogd, дето ги пише някъде, имате ли някаква по-специална идея за тоя колектор?

**Comment by ignisf** [comment]
Не съм измислил още схемата на hostname-овете на ap-тата, но вероятно ще са нещо от сорта на ap-<place>-<ac/an/legacy>-<number>

**Comment by ignisf** [comment]
> Отделно стандартен сислог стрийм ли ще е? Със всичките facility/priority комбота или просто на някое от локалните ще блъскаме?

Не съм сигурен, че разбирам какво питаш, но на OpenWRT сислога поддържа пренасочване към отдалечена система. http://wiki.openwrt.org/doc/uci/system

Аз предпочитам да праща по UDP

**Comment by krokodilerian** [comment]
И аз предпочитам по UDP.

**Comment by zeridon** [comment]
@ignisf имах предвид ще се пращат ли месиджи от типа `kern.warn blq something` или ще са само във примерно `local0.* tag whatever`

Иначе за софтуер все ми е тая. Скоро не съм си играл със rsyslog така че нищно не пречи да е това.

**Comment by eniac111** [comment]
Може да се пробваме с нещо като influxdb/fluentd или logstash/kibana?

**Comment by ignisf** [comment]
Не ни трябват сложни неща, само да ни се събират на едно място логовете

**Comment by robotpanic** [comment]
Има ли вече готов naming-convention за всичките devices?

**Comment by ignisf** [comment]
Има за AP-тата
`ap-chamber-1-ac`, `ap-bulgaria-2-ac`, `ap-lobby-1-an`, `ap-lobby-2-legacy`

**Comment by zeridon** [comment]
на самия централен сислог му е се тая как се казват (не резолвва). Ако е необходимо ще се пусне резолюцията.

**Comment by ignisf** [comment]
Done
