### ISSUE TITLE
Да се съберат ключовете на NOC

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#34]
- [x] Петко (@ignisf) https://petko.me/pubkey.txt
- [x] Васил (@krokodilerian) https://vasil.ludost.net/maniax.key
- [x] Витков (@zeridon) http://home.getoto.net/keys.pub
- [ ] Влад
- [x] Стефан (@arcopix) https://load.devhex.org/key/stefan.key
- [x] Благо (@eniac111) http://blago.sexy/key.pub

**Comment by krokodilerian** [comment]
https://vasil.ludost.net/maniax.key

**Comment by Arcopix** [comment]
https://load.devhex.org/key/stefan.key

**Comment by zeridon** [comment]
http://home.getoto.net/keys.pub

**Comment by eniac111** [comment]
http://blago.sexy/key.pub

**Comment by zeridon** [comment]
А случайно да имаме кандидати за NOC-аджии?

**Comment by eniac111** [comment]
бих правил мониторинг?

**Comment by neterbg** [comment]
https://moyat.net/files/neter.key
