### ISSUE TITLE
IRC канал

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#37]
- [x] Създаване на каналите
- [x] Createmodes/enforcemodes/topic force
- [x] Добавяне на допълнителни хора в сървисите
- [x] Заключване на #ofnoc (да се сподели паролата)
- [ ] log bot
- [x] bridge bot за слак или каквото ще се ползва за екипна комуникация

**Comment by krokodilerian** [comment]
Трябва да имаме следните irc канали:
#openfest-bulgaria-hall
#openfest-chamber-hall
#openfest-third-hall
(тези са за залите, за задаване на въпроси и дискусии)
#ofnoc - за вътрешна употреба, с парола

**Comment by zeridon** [comment]
Каналите са създадени.

Хората които ще висят в IRC-то да предават въпроси ще трябва да се добавят в сървисите също (или бот-а който ще мениджва канала)

**Comment by zeridon** [comment]
12360d302c74f255fb02766539db98b652bb446a adds Slack-to-IRC bidirectional sync bot. Sample org was created in slack.

**Comment by zeridon** [comment]
Бота си върви и си бриджва и си логва.

Ако на някой му трябват канали да ми пише някак.
