### ISSUE TITLE
Web/mobile-friendly messenger (slack)

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#38]

**Comment by eniac111** [comment]
Mattermost / Rocker Chat? 

Идеята е да се използва от екипа?

**Comment by zeridon** [comment]
Създадох примерна организация колкото да го тествам + интеграция с IRC (http://openfest2015.slack.com). Оказва се че фри акаунтите не могат да канят guest юзери така че може би просто ще се наложи да се пусне някакво webirc или подобно.

**Comment by zeridon** [comment]
Акаунта е създаден и хората са поканени

**Comment by zeridon** [comment]
- [ ] @lyubo1 ?
