### ISSUE TITLE
Радиостанции и handsfree-та за тях

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#39]

**Comment by lz1irq** [comment]
Ще се опитам до няколко дена да кажа точна бройка, която мога да намеря (евентуално и с някакви хендсфрита).

**Comment by krokodilerian** [comment]
@lz1irq , ако кажеш и откъде да поръчаме handsfree-та, може да вземем някакво количество (стига да е наблизо).

**Comment by lz1irq** [comment]
@krokodilerian единственият вариант, който е наблизо, е едно магазинче на Илиянци (номер 3671), където се продават радиостанции и аксесоари за тях. Не гарантирам обаче, че ще имат налични, а и ще са по-скъпи.

**Comment by lz1irq** [comment]
До момента:
* 1 станция от мен
* 3 от офиса
* 5 от познат радиолюбител
* 2 от друг човек
* 2 от vloo
* 2 от Пешо

Общо - 15. За хендсфрита още не мога да кажа, но мисля, че ще мога да намеря още няколко станции.

**Comment by lz1irq** [comment]
Проверих цените на хендсфритата на Илиянци - 6 лв/брой, като не предлагат отстъпки за по-голямо количество (например 10 бр.). Но предвид това, че някаква част от станциите вече имат хендсфрита може и да не се наложи.

**Comment by krokodilerian** [comment]
Колко станции нямаха? Мисля, че 10бр. ще ни стигнат, аз мога да ти дам парите.

**Comment by zeridon** [comment]
@lz1irq как сме със станциите?

**Comment by lz1irq** [comment]
В момента в лаба съм събрал 10 радиостанции, 7 от тях имат хендсфрита.
Чакаме:
* още 2 от Пешо - не съм сигурен дали имат хендсфрита, мисля, че имат
* 2 от vloo (вероятно са в работната стая) - имат хендсфрита
* Стоил да донесе хендсфрита и зарядни за двете негови. (такова зарядно мога да взема от офиса).

Всички събрани станции са с програмирани канали и CTCSS (не убива смущенията изцяло, но помага поне малко срещу това да слушаме как си говорят кранисти, хамали и т.н.).

Тази вечер ще мина през лаба, за да видя последно какво има и колко хендсфрита ще ни трябват още. Петък сутринта ще се разходя до Илиянци, за да купя (вероятно ще се наложи).
