### ISSUE TITLE
Да се измисли, тества и конфигурира схемата за потискане на broadcast и multicast

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#4]
Трябва да имаме вързана инфраструктура в лаба за тестване

- [x] Филтриране на трафика с ebtables на AP-тата
- [ ] ~~Филтриране на трафика с MAC ACLs на суичовете~~
- [x] Client isolation
- [x] Настройване на ARP/NDP таймерите, state таймерите и DHCP лийсовете
- [x] Forced forwarding през рутера

**Comment by zeridon** [comment]
Има интересни трикове със sysctl-to https://klaver.it/linux/sysctl.conf

**Comment by krokodilerian** [comment]
Няколко пъти го говорим това, и все не го записваме, та да взема да опиша ква ни е идеята и до какви неща стигнахме:

Накратко, трябва да няма broadcast и multicast във wifi-то, понеже само пречи. Повечето такъв трафик директно можем да го отстреляме, като протоколите, за които трябва да помислим да работят, са ARP, dhcp за ipv4 и ND за ipv6.

Принципно в wifi мрежата broadcast-а се преизпраща от AP-то, така че реално можем още в него да го консумираме.

Базовата идея е да направим нещо-като-forced-forwading:

* Всички ARP requests от клиенти се изпращат само до router-а, който им отговаря със себе си;
* Всички arp replies от клиенти, без значение за кого са се пращат до само router-а;
* Всички dhcp request-и се пращат директно към router-а;
* Router-а поддържа arp таблица, в която знае всички клиенти и отговаря.

За ND имам да помисля още малко какви tool-ове имаме.

**Comment by ignisf** [comment]
За ipv6 има https://github.com/vanhauser-thc/thc-ipv6

**Comment by zeridon** [comment]
За вифитата - client isolation + proxy-arp може би ще решат проблема. или другия вариант е ап-тата реално да се използват като тъпи range-extender-и (ако може така да се каже). Или просто да се набриджнат. (С такива неща не ми се е налагало да си играя така че ако бъркам не е умишлено)

**Comment by ignisf** [comment]
ebtables rule:

`ebtables -A FORWARD -i wlan+ -o wlan+ -j DROP`

```
                          TCP (Mb/s)  UDP(KP/s)
HW Switch                        935         70
Bridge                           926         30
Bridge + ebtables                830         30
Bridge + ebtables + rule         768         30
```

**Comment by ignisf** [comment]
AP Client isolate работи между клиенти в един и същ BSS, което означава, че няма нужда от ebtables на legacy устройствата.

**Comment by ignisf** [comment]
```
net.ipv4.neigh.default.gc_interval = 30
net.ipv4.neigh.default.gc_stale_time = 60
net.ipv4.neigh.default.gc_thresh1 = 128
net.ipv4.neigh.default.gc_thresh2 = 512
net.ipv4.neigh.default.gc_thresh3 = 1024
net.ipv4.route.gc_elasticity = 8
net.ipv4.route.gc_interval = 60
net.ipv4.route.gc_min_interval = 0
net.ipv4.route.gc_min_interval_ms = 500
net.ipv4.route.gc_thresh = -1
net.ipv4.route.gc_timeout = 300

net.ipv6.neigh.default.gc_interval = 30
net.ipv6.neigh.default.gc_stale_time = 60
net.ipv6.neigh.default.gc_thresh1 = 128
net.ipv6.neigh.default.gc_thresh2 = 512
net.ipv6.neigh.default.gc_thresh3 = 1024
net.ipv6.route.gc_elasticity = 9
net.ipv6.route.gc_interval = 30
net.ipv6.route.gc_min_interval = 0
net.ipv6.route.gc_min_interval_ms = 500
net.ipv6.route.gc_thresh = 1024
net.ipv6.route.gc_timeout = 60
```
`net.netfilter.nf_conntrack_tcp_timeout_established = 432000` !!!!

**Comment by ignisf** [comment]
Относно идеята за forced forwarding на @krokodilerian, когато си взимаш IP адрес през DHCP, ако някой ти върне ARP отговор, връщаш NAK. Други коментари по конфигурацията на DHCP сървъра – предлагам дълъг лийс тайм и `ping-check`.

**Comment by ignisf** [comment]
Client isolation чупи откриването на конфликти от DHCP клиентите.

**Comment by zeridon** [comment]
```
net.ipv4.neigh.default.gc_interval = 30
net.ipv4.neigh.default.gc_stale_time = 180
net.ipv4.neigh.default.gc_thresh1 = 128
net.ipv4.neigh.default.gc_thresh2 = 1024
net.ipv4.neigh.default.gc_thresh3 = 2048

net.ipv6.neigh.default.gc_interval = 30
net.ipv6.neigh.default.gc_stale_time = 180
net.ipv6.neigh.default.gc_thresh1 = 128
net.ipv6.neigh.default.gc_thresh2 = 1024
net.ipv6.neigh.default.gc_thresh3 = 2048
```

По скоро мисля че ще е добре 3 минути таймаут за арп и дигане на размерите на таблицата за да не се стига до чистенето и (през деня) `gc_thresh_2` е софт лимит (5 секунди след като се удари се започва forced GC).

**Comment by zeridon** [comment]
```
#Prevent SYN attack, enable SYNcookies (they will kick-in when the max_syn_backlog reached)
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_max_syn_backlog = 4096

# Decrease the time default value for tcp_fin_timeout connection
net.ipv4.tcp_fin_timeout = 7

# Decrease the time default value for connections to keep alive
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# Turn on the tcp_timestamps, accurate timestamp make TCP congestion control algorithms work better
net.ipv4.tcp_timestamps = 1

# Turn on the tcp_window_scaling
net.ipv4.tcp_window_scaling = 1# Increase the maximum amount of option memory buffers
net.core.optmem_max = 65535

# Increase the tcp-time-wait buckets pool size to prevent simple DOS attacks
net.ipv4.tcp_max_tw_buckets = 1440000

# try to reuse time-wait connections, but don't recycle them (recycle can break clients behind NAT)
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_tw_reuse = 1

# Enable Explicit Congestion Notification (RFC 3168), disable it if it doesn't work for you
net.ipv4.tcp_ecn = 1
net.ipv4.tcp_reordering = 3

# How many times to retry killing an alive TCP connection
net.ipv4.tcp_retries2 = 15
net.ipv4.tcp_retries1 = 3
```
Може и да е полезно (от линка дето пуснах най-отгоре)

**Comment by ignisf** [comment]
В момента е:

```
/usr/sbin/ebtables -A FORWARD -i wlan+ -o wlan+ -j DROP
/usr/sbin/ebtables -A FORWARD -i wlan+ -s 00:1e:0b:d9:bb:6a -j DROP
/usr/sbin/ebtables -A FORWARD -i eth+ -o wlan+ -s ! 00:1e:0b:d9:bb:6a -j DROP
```

**Comment by ignisf** [comment]
За forced forwarding, cc @zeridon @krokodilerian :

    net.ipv6.conf.eth1/102.proxy_ndp = 1
    net.ipv6.conf.eth1/102.proxy_ndp=1
    net.ipv4.conf.eth1/102.proxy_arp=1
    net.ipv4.conf.eth1/102.proxy_arp_pvlan=1

**Comment by ignisf** [comment]
@krokodilerian е направил горното
