### ISSUE TITLE
Да се сменят BSSID-тата по подразбиране на всички AP-та

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#43]
`/etc/config/wireless/`:
```
config wifi-iface
...
	option macaddr "aa:bb:cc:dd:ee:ff"
```

**Comment by krokodilerian** [comment]
Според https://en.wikipedia.org/wiki/MAC_address, ако mac-а почва с 02: е локално администриран, т.е. ако направим нещо като 02:0N:AA:BB:CC:DD, където N е номерът на интерфейса (wlan0, wlan1) и АА.BB.CC.DD е IP-то на AP-то трябва да върши прекрасна работа.

**Comment by ignisf** [comment]
Done

`02:00:0f:20:15:XY`

X - номер на AP
Y - номер на wlan
