### ISSUE TITLE
Антистатични напръстници

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-network#44]

**Comment by zeridon** [comment]
Имам няколко антистатични гривни (така де заземяващи) от тоя тип https://upload.wikimedia.org/wikipedia/commons/b/bb/Antistatic_wrist_strap.jpg.

Ако вършат работа колко ще трябват че да погледна.

**Comment by neterbg** [comment]
За напръстниците, не остана достатъчно време за безплатна/евтина доставка от международните продавалници, 50-60 (и нагоре) лева за по-бърза доставка ми се струва неоправдано за случая, а не съм виждал и не намирам да се продават в България. Цели ръкавици има в България. Единият вариант е да се вземат латексови и да се изрежат само пръсти от тях, ако създават проблеми за целодневно носене в цялостен вид. Другият вариант е ръкавици от този вид:
http://www.avto.bim.bg/Antistatichni-rabotni-rukavici_pr51902.html
или този вид:
http://dice.bg/jakemy-esd-gloves-xl-specialni-antistatichni-rabotni-rykavici-za-remontni-deinosti-bulk-item22871
Вторите са 5 в комплект за тази цена. По-скъпи са от напръстниците, но ще ги имаме навреме, ще могат да се преизползват повече, а и не всички ще пипат техника (някои не и едновременно), така че бройката може да се редуцира.

**Comment by ignisf** [comment]
Засега затваряме в такъв случай

**Comment by ignisf** [comment]
@zeridon, носи ги, поне за видео екипите да има, ако решат да ги ползват
