### ISSUE TITLE
Устройство за временно пускане на internet за филхармонията

### ISSUE THREAD

**Issue by krokodilerian** [OpenFest/openfest-network#46]
Трябва да сложим едно устройство, което да пуска wifi и wired свързаност в зала България на 02.11. Настройките се очакват и ще ги пусна тук, предлагам да харесаме едно от AP-тата, да го настроим като router и да метнем него.

@ignisf, ще ми харесаш ли едно такова, и към събота/неделя да го настроим?

**Comment by krokodilerian** [comment]
IPv4 мрежови настройки:
94.26.15.85/255.255.255.224
GW 94.26.15.65
Трябва да се обадим да set-нат mac-а там като се сложи устройството.

**Comment by krokodilerian** [comment]
Имаше грешка в предишните адреси, ето тва са ни настройките:

IPv4 -
Network:  185.108.141.88/30
NetX: 185.108.141.89
FOP: 185.108.141.90

IPv6 -
Network: 2a01:b760:1::/127
NetX: 2a01:b760:1::0
FOP: 2a01:b760:1::1

Static IPv6 networks:
2a01:b760:abc:2::/64
2a01:b760:abc:3::/64
2a01:b760:abc:4::/64
2a01:b760:abc:5::/64

**Comment by ignisf** [comment]
шур

**Comment by eniac111** [comment]
Мога да взема някакъв по- малък tp-link, за да не пипаме сетъпите на
AP-тата.

**Comment by ignisf** [comment]
done
